In [70]:
#Importing Pandas from thr library
import pandas as pd

# Read the Excel file
df = pd.read_excel("Pending Incident.xlsx", engine='openpyxl')

#Create a new column called "Date"
df['Date'] = pd.to_datetime(df['Created']).dt.date

# Create a new column "Age", and calculate the value in days count (Today - Created)
df['Age'] = (pd.Timestamp.now() - pd.to_datetime(df['Date'])).dt.days

# Filter the DataFrame
df = df[df['Age'] > 0]

# Create a pivot table using the "assignment_group" column
pivot_table = pd.pivot_table(df, values='Number', index='Assignment group', columns='Age', aggfunc='count')

# Fill NaN values with zeros
pivot_table = pivot_table.fillna(0)

# Format the values as integers (no decimals)
pivot_table = pivot_table.astype(int)

# Append the grand total row to the pivot table
pivot_table_styled = pd.concat([pivot_table])

# Add the total column to the pivot table
pivot_table_styled['Total'] = pivot_table_styled.sum(axis=1)

# Add the total row to the pivot table
pivot_table_styled.loc['Total'] = pivot_table_styled.sum()

# Highlight integer values in red
def highlight_integers(val):
    if isinstance(val, int):
        return 'color: red'
    else:
        return ''

# Apply the style to the pivot table
pivot_table_styled = pivot_table_styled.style.applymap(highlight_integers)

# Set the style for the first four columns (0, 1, 2, 3) to black color
pivot_table_styled = pivot_table_styled.set_properties(subset=pivot_table_styled.columns[:3], color="black")

# Set the style for the "Total" column to black color
pivot_table_styled = pivot_table_styled.set_properties(subset=['Total'], color="black")

# Assign the styled pivot table to DOR_Pending_Incident
DOR_Pending_Incidents = pivot_table_styled

# Renaming the Index Name
DOR_Pending_Incidents.index.name = "Infrastructure Teams"

# Renaming the Column Name
DOR_Pending_Incidents.columns.name = "Pending Incidents Age"

# Display the styled pivot table
DOR_Pending_Incidents

<ipython-input-70-6c526f14fcfb>:42: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  pivot_table_styled = pivot_table_styled.style.applymap(highlight_integers)